name: jungler
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.4.0
  cupertino_icons: ^1.0.5
  flame_audio: ^1.3.2
  hive: ^2.2.3
  flutter_riverpod: ^2.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  freezed: ^2.2.0
  json_serializable: ^6.5.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    - assets/audio/
    - assets/images/parallax/
    - assets/images/parallax/plain/
    - assets/images/enemies/angry_pig/
    - assets/images/enemies/bat/
    - assets/images/enemies/blue_bird/
    - assets/images/enemies/bee/
    - assets/images/enemies/bunny/
    - assets/images/enemies/chameleon/
    - assets/images/enemies/chicken/
#    - assets/images/enemies/duck/
#    - assets/images/enemies/fat_bird/
    - assets/images/enemies/ghost/
    - assets/images/enemies/mushroom/
#    - assets/images/enemies/plant/
    - assets/images/enemies/radish/
    - assets/images/enemies/rino/
    - assets/images/enemies/rocks/
    - assets/images/enemies/skull/
    - assets/images/enemies/slime/
    - assets/images/enemies/snail/
    - assets/images/enemies/trunk/
    - assets/images/enemies/turtle/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
